pederapido:
  origenspermitidas: http://localhost:4200,http://ec2-44-203-56-241.compute-1.amazonaws.com:8081
  
url-websocket: http://52.70.86.211:8090/websocket

com: 
  kb: 
    jwt: 
      aws: 
        userPoolId: "us-east-1_0sVdlrSMk" 
        region: "us-east-1"
        
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: 
    
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
      
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update